version: '2'

services:
  web:
    image: node:7.7
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
    command: sh -c 'npm start'
    ports:
      - "10000:8080"
    environment:
      NODE_HOST: redis
